server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:80
      discovery:
        cluster-name: GX
    gateway:
      routes:
        - id: user-service #路由表示。唯一
          uri: lb://userservice #目标地址
          predicates: #路由断言
            - Path=/user/**
        - id: order-service #路由表示。唯一
          uri: lb://orderservice #目标地址
          predicates: #路由断言
            - Path=/order/**
          filters: #过滤器，可处理请求和响应
            - AddRequestHeader=Truth,Wei #加请求头信息
      default-filters: #默认过滤器,对所有路由有效
        - AddRequestHeader=Truth2,Wei
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:8090"
              - "http://www.leyou.com"
              - "*"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期